<!DOCTYPE html>
	<html>
	
		<head>
			<title>Nascar</title>
		</head>
		
		<body>
			<!-- Image Map Generated by http://www.image-map.net/ -->
                     <img src="C:\Users\rupp_\OneDrive\Documents\GitHub\CSIS1430\htdocs\image-map\img\car.jpeg" usemap="#Nascar">

                     <map name="Nascar">
                             <area href="https://www.mcdonalds.com/us/en-us.html" coords="2261,1312,2349,1391" shape="rect">
                             <area href="https://www.mobil.com/en/lubricants/for-personal-vehicles/our-products/motor-oils/mobil-1-motor-oil-products" coords="2738,1176,2908,1237" shape="rect">
                             <area href="https://www.nascar.com/" coords="1526,1213,1656,1290" shape="rect">
                             <area href="https://www.toyota.com/" coords="563,1237,42" shape="circle">
                             <area href="https://www.drpepper.com/en" coords="2787,1320,69" shape="circle">
                             <area href="https://www.goodyear.com/" coords="1340,1543,194" shape="circle">
                             <area href="https://www.doordash.com/?ignore_splash_experience=true&amp;https://www.doordash.com/?ignore_splash_experience=true&amp;utm_source=Bing&amp;utm_medium=SEMb&amp;utm_campaign=CX_US_SE_SB_BI_ACQ_TMTXXX_386526256_+BR_ACQ_INMKT_GenDeliveryxx_EVG_CPAx_EXA_TZMST_EN_EN_X_DOOR_BN_SE_TXT_XXXXXXXXXX&amp;utm_term=doordash%20com&amp;utm_content=1212761770101589&amp;kclickid=_k_a5ead0baf2e41f443fc2b006deacfcc3_k_&amp;utm_adgroup_id=1212761770101589&amp;utm_creative_id=&amp;utm_keyword_id=kwd-75797929650968:loc-4128&amp;msclkid=a5ead0baf2e41f443fc2b006deacfcc3&amp;gclid=CIWOltf0gfECFfCNxQIdttoNTA&amp;gclsrc=ds" coords="718,807,706,912,1029,1110,955,1121,709,980,692,1098,930,1248,1099,1220,1241,1166,1207,1087" shape="poly">
                             <area href="https://en.wikipedia.org/wiki/Michael_Jordan" coords="1860,1261,1803,1369,1831,1377,1786,1417,1690,1564,1995,1521,2075,1386,2069,1366,2097,1346,2159,1210,2027,1236,2021,1250,1998,1227" shape="poly">
                             <area href="https://en.wikipedia.org/wiki/Safety_in_NASCAR" coords="1755,1097,1764,1177,2010,1134,2278,1083,2524,1018,2583,967,2516,897,2431,863,2343,852,2216,852,2024,874,1897,965" shape="poly">
                     </map>
			
			<ul>
				<li>McDonalds logo</li>
				<li>Mobil One logo</li>
				<li>Nascar logo above front tire</li>
				<li>Toyota logo front of car</li>
				<li>Dr Pepper Logo</li>
				<li>Front tire</li>
				<li>Doordash logo on hood</li>
				<li>Number 23 side of car</li>
				<li>Driver side window</li>
			</ul>
			
			<p> I wanted to make sure I had an image that was both something I liked and that would allow me multiple options for links. I decided to choose Nascar #23 of Bubba Wallace. 
			       I chose this car for a few reasons, first I follow him in Nascar, second this car is owned by Michael Jordan and another driver I follow Denny Hamlin. Third, because Bubba Wallace is 
				sponsered by a few companies that I like, so the links that I selected, for the most part are companies I like. </p>
				
			<p> The first logo I selected was the McDonald's logo on the back of the car. I chose this becuase, not only is it a very familiar logo to almost everyone, but I enjoy their food, especially their chicken nuggets.
			       The Next logo is the Mobil One logo, and although this sounds like a cell phone company, it is acutally a motor oil company that is well known in Nascar. The next part I chose was the Nascar logo, I thought
				 it would be appropriate,  since it is a Nascar. I selected the Toyota logo at the front next, because after seeing how this car runs and how fast it is, I purchased  a Camry for myself, and it is pretty fast.</p>
			
			<p> The Dr. Pepper logo was the most obvious choice for me, since it is my favorite drink. The front tire will take you too the GoodYear website, and they actually supply all the tires for Nascar, so I thought this 
			       would be a good idea to incude them. Doordash, was a life saver through the pandemic and one of Bubba Wallace's major sponsors so I figured I needed to add them. I chose the 23 will take you to information
				for Michael Jordan, since his number was 23 when he played basketball and since he is part owner of this car and finally I selected the drivers side windwo netting, becuase saftey is a huge part of Nascar
				and although it doesn't look like much, there is a lot of thought that goes into driver's safety and small things like the netting can make a huge difference. </p>

			      
		</body>
	</html>
